version: 2.1
jobs:
  deploy_lambda:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Configure AWS CLI
      - run:
          name: Configure AWS CLI
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/config
            echo "region = us-east-1" >> ~/.aws/config
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

      # Deploy Lambda function
      - run:
          name: Deploy Lambda function
          command: |
            aws lambda update-function-code --function-name daily-ingestion --zip-file fileb://VoltWise/Data_Ingestion/Lambda/daily_ingestion_lambda_function.py
